In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
data = pd.read_csv('./111.csv')
selected_data = data.iloc[:8698, 22:]
print(selected_data)

       Kh_H2.1  Kh_CH4.1   void fraction [widom]   supercell volume [A^3]  \
0     0.046462  0.806263                0.774002              37137.01067   
1     0.043839  0.285863                0.755095              88815.76359   
2     0.042089  0.628554                0.527499              82897.38092   
3     0.044269  0.450933                0.727666              33884.78447   
4     0.043694  0.388438                0.714711              42906.37871   
...        ...       ...                     ...                      ...   
8693  0.045286  0.544446                0.674595             143246.12490   
8694  0.046333  0.611321                0.678067              47431.63817   
8695  0.040306  0.287475                0.610998              86927.30120   
8696  0.040306  0.287475                0.611235              86927.30120   
8697  0.044179  0.349743                0.762879              43368.64861   

      dimensions   density [kg/m^3]   surface area [m^2/g]  \
0            

In [2]:
numpy_array = selected_data.to_numpy()
print (numpy_array)



[[4.64616000e-02 8.06263000e-01 7.74002000e-01 ... 1.00000000e+00
  1.14969000e-04 1.00000000e+00]
 [4.38391000e-02 2.85863000e-01 7.55095000e-01 ... 2.00000000e+00
  2.29938000e-04 1.00000000e+00]
 [4.20891000e-02 6.28554000e-01 5.27499000e-01 ... 3.00000000e+00
  3.44907000e-04 1.00000000e+00]
 ...
 [4.03058000e-02 2.87475000e-01 6.10998000e-01 ... 8.69600000e+03
  9.99770062e-01 0.00000000e+00]
 [4.03058000e-02 2.87475000e-01 6.11235000e-01 ... 8.69700000e+03
  9.99885031e-01 0.00000000e+00]
 [4.41792000e-02 3.49743000e-01 7.62879000e-01 ... 8.69800000e+03
  1.00000000e+00 0.00000000e+00]]


In [3]:
from sklearn.preprocessing import MinMaxScaler
Mm = MinMaxScaler()
X=selected_data.iloc[:, :].to_numpy()
print(X[1])
data = Mm.fit_transform(X)#归一化处理，为后面的监督学习

[4.38391000e-02 2.85863000e-01 7.55095000e-01 8.88157636e+04
 3.00000000e+00 3.41629701e+02 4.36050000e+03 1.23942455e+02
 1.11600000e+03 0.00000000e+00 8.28000000e+02 2.88000000e+02
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
 2.00000000e+00 7.00000000e+00 2.23341000e+01 2.18589100e+01
 2.23341000e+01 2.00000000e+00 2.29938000e-04 1.00000000e+00]


In [4]:
from sklearn.model_selection import train_test_split

# 提取特征数据和目标变量
features = numpy_array[:, :-4]
features1 = numpy_array[:, :-4]
target = numpy_array[:, -1]
print(target)
print(features)
#X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=999)
#X_train1, X_test1, y_train1, y_test1 = train_test_split(features1, target, test_size=0.3, random_state=999)

[1. 1. 1. ... 0. 0. 0.]
[[ 0.0464616  0.806263   0.774002  ... 25.        17.58356   16.10518  ]
 [ 0.0438391  0.285863   0.755095  ...  7.        22.3341    21.85891  ]
 [ 0.0420891  0.628554   0.527499  ...  7.         7.89938    5.16156  ]
 ...
 [ 0.0403058  0.287475   0.610998  ...  5.        10.83553    7.13014  ]
 [ 0.0403058  0.287475   0.611235  ...  5.        10.83553    7.13014  ]
 [ 0.0441792  0.349743   0.762879  ...  9.        13.47683    9.8917   ]]


In [14]:
import numpy as np
from sklearn.model_selection import train_test_split

# 原始的训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=999)

# 找到标签为1的索引
index_of_ones = np.where(y_train == 1)[0]

# 复制标签为1的数据多份
num_copies_1 = 50  # 假设需要复制20份
index_to_copy_1 = np.random.choice(index_of_ones, size=len(index_of_ones)*num_copies_1, replace=True)

# 将标签为1的数据复制多份并添加到训练集中
X_train_copies = np.concatenate([X_train, X_train[index_to_copy_1]])
y_train_copies = np.concatenate([y_train, y_train[index_to_copy_1]])

# 找到标签为2的索引
index_of_twos = np.where(y_train == 2)[0]

# 复制标签为2的数据多份
num_copies_2 = 10  # 假设需要复制10份
index_to_copy_2 = np.random.choice(index_of_twos, size=len(index_of_twos)*num_copies_2, replace=True)

# 将标签为2的数据复制多份并添加到训练集中
X_train_copies = np.concatenate([X_train_copies, X_train[index_to_copy_2]])
y_train_copies = np.concatenate([y_train_copies, y_train[index_to_copy_2]])

index_of_0s = np.where(y_train == 0)[0]

# 复制标签为2的数据多份
num_copies_0 = 2  # 假设需要复制10份
index_to_copy_0 = np.random.choice(index_of_0s, size=len(index_of_0s)*num_copies_0, replace=True)

# 将标签为2的数据复制多份并添加到训练集中
X_train_copies = np.concatenate([X_train_copies, X_train[index_to_copy_0]])
y_train_copies = np.concatenate([y_train_copies, y_train[index_to_copy_0]])

In [15]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

# 建立SVM模型
svm = SVC(kernel='linear', random_state=50,C= 1)
svm.fit(X_train_copies, y_train_copies)
predictions_svm = svm.predict(X_test)

# 打印SVM分类报告和混淆矩阵
print("SVM Classification Report:")
print(classification_report(y_test, predictions_svm))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_svm))

# 建立随机森林模型
rf = RandomForestClassifier(n_estimators=100, random_state=50)
rf.fit(X_train_copies, y_train_copies)
predictions_rf = rf.predict(X_test)

# 打印随机森林分类报告和混淆矩阵
print("Random Forest Classification Report:")
print(classification_report(y_test, predictions_rf))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_rf))

# 建立梯度提升树模型
gbc = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=4, random_state=50)
gbc.fit(X_train_copies, y_train_copies)
predictions_gbc = gbc.predict(X_test)

# 打印梯度提升树分类报告和混淆矩阵
print("Gradient Boosting Classification Report:")
print(classification_report(y_test, predictions_gbc))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_gbc))


SVM Classification Report:
              precision    recall  f1-score   support

         0.0       0.87      0.32      0.46      1951
         1.0       0.08      0.72      0.14       126
         2.0       0.35      0.46      0.40       533

    accuracy                           0.37      2610
   macro avg       0.43      0.50      0.33      2610
weighted avg       0.73      0.37      0.44      2610

Confusion Matrix:
[[618 901 432]
 [ 22  91  13]
 [ 71 218 244]]
Random Forest Classification Report:
              precision    recall  f1-score   support

         0.0       0.84      0.95      0.90      1951
         1.0       0.55      0.21      0.30       126
         2.0       0.73      0.50      0.59       533

    accuracy                           0.82      2610
   macro avg       0.71      0.55      0.60      2610
weighted avg       0.81      0.82      0.80      2610

Confusion Matrix:
[[1858   11   82]
 [  84   26   16]
 [ 258   10  265]]
Gradient Boosting Classification Repo

In [16]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

# 建立决策树模型
dt = DecisionTreeClassifier(random_state=50)
dt.fit(X_train_copies, y_train_copies)
predictions_dt = dt.predict(X_test)

# 打印决策树分类报告和混淆矩阵
print("Decision Tree Classification Report:")
print(classification_report(y_test, predictions_dt))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_dt))

# 建立k-Nearest Neighbors模型
knn = KNeighborsClassifier()
knn.fit(X_train_copies, y_train_copies)
predictions_knn = knn.predict(X_test)

# 打印k-Nearest Neighbors分类报告和混淆矩阵
print("k-Nearest Neighbors Classification Report:")
print(classification_report(y_test, predictions_knn))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_knn))

# 建立Logistic Regression模型
lr = LogisticRegression(max_iter=1000, random_state=50)
lr.fit(X_train_copies, y_train_copies)
predictions_lr = lr.predict(X_test)

# 打印Logistic Regression分类报告和混淆矩阵
print("Logistic Regression Classification Report:")
print(classification_report(y_test, predictions_lr))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_lr))


Decision Tree Classification Report:
              precision    recall  f1-score   support

         0.0       0.84      0.84      0.84      1951
         1.0       0.21      0.25      0.23       126
         2.0       0.51      0.49      0.50       533

    accuracy                           0.74      2610
   macro avg       0.52      0.53      0.52      2610
weighted avg       0.74      0.74      0.74      2610

Confusion Matrix:
[[1635   87  229]
 [  74   32   20]
 [ 240   31  262]]
k-Nearest Neighbors Classification Report:
              precision    recall  f1-score   support

         0.0       0.83      0.76      0.79      1951
         1.0       0.19      0.24      0.21       126
         2.0       0.42      0.51      0.46       533

    accuracy                           0.68      2610
   macro avg       0.48      0.50      0.49      2610
weighted avg       0.71      0.68      0.70      2610

Confusion Matrix:
[[1487  107  357]
 [  73   30   23]
 [ 239   24  270]]
Logistic Reg

/home/qiuyong/.conda/envs/LiIonMl/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [48]:
import numpy as np
from sklearn.metrics import accuracy_score
# 假设predictions_rf、predictions_dt、predictions_knn是随机森林、决策树和k-Nearest Neighbors的预测结果
# 分别对应模型的类别概率
probs_rf = rf.predict_proba(X_test)
probs_dt = dt.predict_proba(X_test)
probs_knn = knn.predict_proba(X_test)

# 对预测类型1的加权平均
weighted_avg_probs = 0.4 * probs_rf[:, 0] + 0.3 * probs_dt[:, 0] + 0.3 * probs_knn[:, 0]
#print(probs_rf[:, 0])
# 设置阈值，当加权平均概率超过阈值时，认定为类型1
threshold = 0.4

# 根据阈值判断最终的预测类型
final_predictions = np.where(weighted_avg_probs > threshold,0,predictions_rf)
# 计算准确率
accuracy = accuracy_score(y_test, final_predictions)
conf_matrix = confusion_matrix(y_test, final_predictions)

print("混淆矩阵:")
print(conf_matrix)
print("加权平均预测准确率:", accuracy)

混淆矩阵:
[[1903    7   41]
 [  89   23   14]
 [ 312    7  214]]
加权平均预测准确率: 0.8199233716475096


In [5]:
import numpy as np
from sklearn.model_selection import train_test_split

# 原始的训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=999)

# 找到标签为1的索引
index_of_ones = np.where(y_train == 1)[0]

# 复制标签为1的数据多份
num_copies_1 = 30  # 假设需要复制20份
index_to_copy_1 = np.random.choice(index_of_ones, size=len(index_of_ones)*num_copies_1, replace=True)

# 将标签为1的数据复制多份并添加到训练集中
X_train_copies = np.concatenate([X_train, X_train[index_to_copy_1]])
y_train_copies = np.concatenate([y_train, y_train[index_to_copy_1]])

# 找到标签为2的索引
index_of_twos = np.where(y_train == 2)[0]

# 复制标签为2的数据多份
num_copies_2 = 10  # 假设需要复制10份
index_to_copy_2 = np.random.choice(index_of_twos, size=len(index_of_twos)*num_copies_2, replace=True)

# 将标签为2的数据复制多份并添加到训练集中
X_train_copies = np.concatenate([X_train_copies, X_train[index_to_copy_2]])
y_train_copies = np.concatenate([y_train_copies, y_train[index_to_copy_2]])

index_of_0s = np.where(y_train == 0)[0]

# 复制标签为2的数据多份
num_copies_0 = 2  # 假设需要复制10份
index_to_copy_0 = np.random.choice(index_of_0s, size=len(index_of_0s)*num_copies_0, replace=True)

# 将标签为2的数据复制多份并添加到训练集中
X_train_copies = np.concatenate([X_train_copies, X_train[index_to_copy_0]])
y_train_copies = np.concatenate([y_train_copies, y_train[index_to_copy_0]])

In [6]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

# 建立SVM模型
svm = SVC(kernel='linear', random_state=50,C= 1)
svm.fit(X_train_copies, y_train_copies)
predictions_svm = svm.predict(X_test)

# 打印SVM分类报告和混淆矩阵
print("SVM Classification Report:")
print(classification_report(y_test, predictions_svm))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_svm))

# 建立随机森林模型
rf = RandomForestClassifier(n_estimators=100, random_state=50)
rf.fit(X_train_copies, y_train_copies)
predictions_rf = rf.predict(X_test)

# 打印随机森林分类报告和混淆矩阵
print("Random Forest Classification Report:")
print(classification_report(y_test, predictions_rf))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_rf))

# 建立梯度提升树模型
gbc = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=4, random_state=50)
gbc.fit(X_train_copies, y_train_copies)
predictions_gbc = gbc.predict(X_test)

# 打印梯度提升树分类报告和混淆矩阵
print("Gradient Boosting Classification Report:")
print(classification_report(y_test, predictions_gbc))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_gbc))

SVM Classification Report:
              precision    recall  f1-score   support

         0.0       0.86      0.52      0.65      1951
         1.0       0.11      0.48      0.17       126
         2.0       0.37      0.60      0.46       533

    accuracy                           0.54      2610
   macro avg       0.45      0.53      0.43      2610
weighted avg       0.72      0.54      0.59      2610

Confusion Matrix:
[[1024  413  514]
 [  42   60   24]
 [ 124   90  319]]
Random Forest Classification Report:
              precision    recall  f1-score   support

         0.0       0.85      0.95      0.90      1951
         1.0       0.59      0.25      0.36       126
         2.0       0.74      0.50      0.60       533

    accuracy                           0.83      2610
   macro avg       0.73      0.57      0.62      2610
weighted avg       0.81      0.83      0.81      2610

Confusion Matrix:
[[1858   12   81]
 [  79   32   15]
 [ 256   10  267]]
Gradient Boosting Classifica

In [7]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

# 建立决策树模型
dt = DecisionTreeClassifier(random_state=50)
dt.fit(X_train_copies, y_train_copies)
predictions_dt = dt.predict(X_test)

# 打印决策树分类报告和混淆矩阵
print("Decision Tree Classification Report:")
print(classification_report(y_test, predictions_dt))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_dt))

# 建立k-Nearest Neighbors模型
knn = KNeighborsClassifier()
knn.fit(X_train_copies, y_train_copies)
predictions_knn = knn.predict(X_test)

# 打印k-Nearest Neighbors分类报告和混淆矩阵
print("k-Nearest Neighbors Classification Report:")
print(classification_report(y_test, predictions_knn))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_knn))

# 建立Logistic Regression模型
lr = LogisticRegression(max_iter=1000, random_state=50)
lr.fit(X_train_copies, y_train_copies)
predictions_lr = lr.predict(X_test)

# 打印Logistic Regression分类报告和混淆矩阵
print("Logistic Regression Classification Report:")
print(classification_report(y_test, predictions_lr))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_lr))

Decision Tree Classification Report:
              precision    recall  f1-score   support

         0.0       0.84      0.85      0.85      1951
         1.0       0.27      0.31      0.29       126
         2.0       0.55      0.50      0.52       533

    accuracy                           0.76      2610
   macro avg       0.55      0.55      0.55      2610
weighted avg       0.75      0.76      0.75      2610

Confusion Matrix:
[[1665   84  202]
 [  69   39   18]
 [ 245   21  267]]
k-Nearest Neighbors Classification Report:
              precision    recall  f1-score   support

         0.0       0.83      0.77      0.80      1951
         1.0       0.20      0.25      0.23       126
         2.0       0.42      0.50      0.46       533

    accuracy                           0.69      2610
   macro avg       0.48      0.51      0.49      2610
weighted avg       0.72      0.69      0.70      2610

Confusion Matrix:
[[1502  103  346]
 [  69   32   25]
 [ 241   23  269]]
Logistic Reg

/home/qiuyong/.conda/envs/LiIonMl/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [13]:
import numpy as np
from sklearn.metrics import accuracy_score
# 假设predictions_rf、predictions_dt、predictions_knn是随机森林、决策树和k-Nearest Neighbors的预测结果
# 分别对应模型的类别概率
probs_rf = rf.predict_proba(X_test)
probs_dt = dt.predict_proba(X_test)
probs_knn = knn.predict_proba(X_test)

# 对预测类型1的加权平均
weighted_avg_probs = 0.4 * probs_rf[:, 0] + 0.3 * probs_dt[:, 0] + 0.3 * probs_knn[:, 0]
#print(probs_rf[:, 0])
# 设置阈值，当加权平均概率超过阈值时，认定为类型1
threshold = 0.4

# 根据阈值判断最终的预测类型
final_predictions = np.where(weighted_avg_probs > threshold,0,predictions_rf)
# 计算准确率
accuracy = accuracy_score(y_test, final_predictions)
conf_matrix = confusion_matrix(y_test, final_predictions)

print("混淆矩阵:")
print(conf_matrix)
print("加权平均预测准确率:", accuracy)

混淆矩阵:
[[1905    8   38]
 [  85   31   10]
 [ 319    9  205]]
加权平均预测准确率: 0.8203065134099616


In [14]:
import numpy as np
from sklearn.metrics import accuracy_score
# 假设predictions_rf、predictions_dt、predictions_knn是随机森林、决策树和k-Nearest Neighbors的预测结果
# 分别对应模型的类别概率
probs_rf = rf.predict_proba(X_test)
probs_dt = dt.predict_proba(X_test)
probs_knn = knn.predict_proba(X_test)

# 对预测类型1的加权平均
weighted_avg_probs = 0.5 * probs_rf[:, 0] + 0.3 * probs_dt[:, 0] + 0.2 * probs_knn[:, 0]
#print(probs_rf[:, 0])
# 设置阈值，当加权平均概率超过阈值时，认定为类型1
threshold = 0.4

# 根据阈值判断最终的预测类型
final_predictions = np.where(weighted_avg_probs > threshold,0,predictions_rf)
# 计算准确率
accuracy = accuracy_score(y_test, final_predictions)
conf_matrix = confusion_matrix(y_test, final_predictions)

print("混淆矩阵:")
print(conf_matrix)
print("加权平均预测准确率:", accuracy)

混淆矩阵:
[[1903    7   41]
 [  85   31   10]
 [ 305    8  220]]
加权平均预测准确率: 0.825287356321839
