In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
data = pd.read_csv('./K.csv')
selected_data = data.iloc[:9000, 22:]
print(selected_data)

        aIM   void fraction [widom]   supercell volume [A^3]  \
0     31.40                0.105459              38509.22698   
1     10.40                0.131969              64604.38487   
2     21.60                0.707530              52695.26737   
3     12.80                0.623734              41430.89922   
4     47.10                0.098176              37817.08628   
...     ...                     ...                      ...   
8995  61.10                0.404401              22412.96386   
8996   5.68                0.836335              83255.73528   
8997  18.40                0.571203              42780.90328   
8998   7.16                0.733253              63185.68060   
8999  18.80                0.632062              41641.98342   

       density [kg/m^3]   surface area [m^2/g]  \
0            944.824172               215.4120   
1            787.966755               537.6830   
2            474.663293              3296.0600   
3            637.096493        

In [10]:
numpy_array = selected_data.to_numpy()
print (numpy_array)



[[3.14000000e+01 1.05459000e-01 3.85092270e+04 ... 1.00000000e+00
  1.00301000e-04 1.00000000e+00]
 [1.04000000e+01 1.31969000e-01 6.46043849e+04 ... 2.00000000e+00
  2.00602000e-04 1.00000000e+00]
 [2.16000000e+01 7.07530000e-01 5.26952674e+04 ... 3.00000000e+00
  3.00903000e-04 1.00000000e+00]
 ...
 [1.84000000e+01 5.71203000e-01 4.27809033e+04 ... 8.99800000e+03
  9.02507523e-01 0.00000000e+00]
 [7.16000000e+00 7.33253000e-01 6.31856806e+04 ... 8.99900000e+03
  9.02607823e-01 0.00000000e+00]
 [1.88000000e+01 6.32062000e-01 4.16419834e+04 ... 9.00000000e+03
  9.02708124e-01 0.00000000e+00]]


In [11]:
from sklearn.preprocessing import MinMaxScaler
Mm = MinMaxScaler()
X=selected_data.iloc[:, :].to_numpy()
print(X[1])
data = Mm.fit_transform(X)#归一化处理，为后面的监督学习

[1.04000000e+01 1.31969000e-01 6.46043849e+04 7.87966755e+02
 5.37683000e+02 1.68277013e+01 3.00000000e+00 8.64000000e+02
 0.00000000e+00 7.20000000e+02 1.92000000e+02 9.60000000e+01
 0.00000000e+00 0.00000000e+00 1.00000000e+00 1.00000000e+00
 4.00000000e+00 6.09599000e+00 5.12149000e+00 6.09599000e+00
 2.00000000e+00 2.00602000e-04 1.00000000e+00]


In [12]:
from sklearn.model_selection import train_test_split

features = numpy_array[:, :-4]
features1 = numpy_array[:, :-4]
target = numpy_array[:, -1]
print(target)
print(features)
#X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=999)
#X_train1, X_test1, y_train1, y_test1 = train_test_split(features1, target, test_size=0.3, random_state=999)

[1. 1. 1. ... 0. 0. 0.]
[[3.14000000e+01 1.05459000e-01 3.85092270e+04 ... 4.00000000e+00
  4.35262000e+00 4.05572000e+00]
 [1.04000000e+01 1.31969000e-01 6.46043849e+04 ... 4.00000000e+00
  6.09599000e+00 5.12149000e+00]
 [2.16000000e+01 7.07530000e-01 5.26952674e+04 ... 0.00000000e+00
  1.61470000e+01 1.46794900e+01]
 ...
 [1.84000000e+01 5.71203000e-01 4.27809033e+04 ... 9.00000000e+00
  1.43605900e+01 1.14247000e+01]
 [7.16000000e+00 7.33253000e-01 6.31856806e+04 ... 9.00000000e+00
  1.29763300e+01 7.75315000e+00]
 [1.88000000e+01 6.32062000e-01 4.16419834e+04 ... 5.00000000e+00
  8.73583000e+00 6.33516000e+00]]


In [13]:
import numpy as np
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=999)


index_of_ones = np.where(y_train == 1)[0]


num_copies_1 = 50  
index_to_copy_1 = np.random.choice(index_of_ones, size=len(index_of_ones)*num_copies_1, replace=True)


X_train_copies = np.concatenate([X_train, X_train[index_to_copy_1]])
y_train_copies = np.concatenate([y_train, y_train[index_to_copy_1]])


index_of_twos = np.where(y_train == 2)[0]


num_copies_2 = 10  
index_to_copy_2 = np.random.choice(index_of_twos, size=len(index_of_twos)*num_copies_2, replace=True)


X_train_copies = np.concatenate([X_train_copies, X_train[index_to_copy_2]])
y_train_copies = np.concatenate([y_train_copies, y_train[index_to_copy_2]])

index_of_0s = np.where(y_train == 0)[0]


num_copies_0 = 2  
index_to_copy_0 = np.random.choice(index_of_0s, size=len(index_of_0s)*num_copies_0, replace=True)


X_train_copies = np.concatenate([X_train_copies, X_train[index_to_copy_0]])
y_train_copies = np.concatenate([y_train_copies, y_train[index_to_copy_0]])

In [14]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

svm = SVC(kernel='linear', random_state=50,C= 1)
svm.fit(X_train_copies, y_train_copies)
predictions_svm = svm.predict(X_test)

print("SVM Classification Report:")
print(classification_report(y_test, predictions_svm))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_svm))

rf = RandomForestClassifier(n_estimators=100, random_state=50)
rf.fit(X_train_copies, y_train_copies)
predictions_rf = rf.predict(X_test)

print("Random Forest Classification Report:")
print(classification_report(y_test, predictions_rf))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_rf))

gbc = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=4, random_state=50)
gbc.fit(X_train_copies, y_train_copies)
predictions_gbc = gbc.predict(X_test)

print("Gradient Boosting Classification Report:")
print(classification_report(y_test, predictions_gbc))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_gbc))


SVM Classification Report:
              precision    recall  f1-score   support

         0.0       0.89      0.56      0.68      1941
         1.0       0.17      0.74      0.28       144
         2.0       0.41      0.59      0.49       615

    accuracy                           0.57      2700
   macro avg       0.49      0.63      0.48      2700
weighted avg       0.74      0.57      0.62      2700

Confusion Matrix:
[[1078  369  494]
 [  17  106   21]
 [ 121  131  363]]
Random Forest Classification Report:
              precision    recall  f1-score   support

         0.0       0.85      0.94      0.89      1941
         1.0       0.69      0.49      0.57       144
         2.0       0.73      0.53      0.62       615

    accuracy                           0.83      2700
   macro avg       0.76      0.65      0.69      2700
weighted avg       0.82      0.83      0.81      2700

Confusion Matrix:
[[1829   10  102]
 [  53   70   21]
 [ 265   21  329]]
Gradient Boosting Classifica

In [15]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=50)
dt.fit(X_train_copies, y_train_copies)
predictions_dt = dt.predict(X_test)

print("Decision Tree Classification Report:")
print(classification_report(y_test, predictions_dt))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_dt))

knn = KNeighborsClassifier()
knn.fit(X_train_copies, y_train_copies)
predictions_knn = knn.predict(X_test)

print("k-Nearest Neighbors Classification Report:")
print(classification_report(y_test, predictions_knn))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_knn))

lr = LogisticRegression(max_iter=1000, random_state=50)
lr.fit(X_train_copies, y_train_copies)
predictions_lr = lr.predict(X_test)

print("Logistic Regression Classification Report:")
print(classification_report(y_test, predictions_lr))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_lr))


Decision Tree Classification Report:
              precision    recall  f1-score   support

         0.0       0.85      0.85      0.85      1941
         1.0       0.43      0.42      0.42       144
         2.0       0.54      0.53      0.54       615

    accuracy                           0.76      2700
   macro avg       0.61      0.60      0.60      2700
weighted avg       0.75      0.76      0.76      2700

Confusion Matrix:
[[1658   39  244]
 [  54   60   30]
 [ 248   41  326]]
k-Nearest Neighbors Classification Report:
              precision    recall  f1-score   support

         0.0       0.83      0.78      0.80      1941
         1.0       0.29      0.32      0.30       144
         2.0       0.44      0.53      0.48       615

    accuracy                           0.70      2700
   macro avg       0.52      0.54      0.53      2700
weighted avg       0.72      0.70      0.70      2700

Confusion Matrix:
[[1505   68  368]
 [  56   46   42]
 [ 245   44  326]]
Logistic Reg

/home/qiuyong/.conda/envs/LiIonMl/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [16]:
import numpy as np
from sklearn.metrics import accuracy_score

probs_rf = rf.predict_proba(X_test)
probs_dt = dt.predict_proba(X_test)
probs_knn = knn.predict_proba(X_test)


weighted_avg_probs = 0.4 * probs_rf[:, 0] + 0.3 * probs_dt[:, 0] + 0.3 * probs_knn[:, 0]

threshold = 0.4

final_predictions = np.where(weighted_avg_probs > threshold,0,predictions_rf)

accuracy = accuracy_score(y_test, final_predictions)
conf_matrix = confusion_matrix(y_test, final_predictions)

print("混淆矩阵:")
print(conf_matrix)
print("加权平均预测准确率:", accuracy)

混淆矩阵:
[[1881    9   51]
 [  69   60   15]
 [ 340   14  261]]
加权平均预测准确率: 0.8155555555555556


In [17]:
import numpy as np
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=999)

index_of_ones = np.where(y_train == 1)[0]

num_copies_1 = 30  
index_to_copy_1 = np.random.choice(index_of_ones, size=len(index_of_ones)*num_copies_1, replace=True)

X_train_copies = np.concatenate([X_train, X_train[index_to_copy_1]])
y_train_copies = np.concatenate([y_train, y_train[index_to_copy_1]])

index_of_twos = np.where(y_train == 2)[0]

num_copies_2 = 10  
index_to_copy_2 = np.random.choice(index_of_twos, size=len(index_of_twos)*num_copies_2, replace=True)

X_train_copies = np.concatenate([X_train_copies, X_train[index_to_copy_2]])
y_train_copies = np.concatenate([y_train_copies, y_train[index_to_copy_2]])

index_of_0s = np.where(y_train == 0)[0]

num_copies_0 = 2  
index_to_copy_0 = np.random.choice(index_of_0s, size=len(index_of_0s)*num_copies_0, replace=True)

X_train_copies = np.concatenate([X_train_copies, X_train[index_to_copy_0]])
y_train_copies = np.concatenate([y_train_copies, y_train[index_to_copy_0]])

In [18]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

svm = SVC(kernel='linear', random_state=50,C= 1)
svm.fit(X_train_copies, y_train_copies)
predictions_svm = svm.predict(X_test)

print("SVM Classification Report:")
print(classification_report(y_test, predictions_svm))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_svm))

rf = RandomForestClassifier(n_estimators=100, random_state=50)
rf.fit(X_train_copies, y_train_copies)
predictions_rf = rf.predict(X_test)

print("Random Forest Classification Report:")
print(classification_report(y_test, predictions_rf))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_rf))

gbc = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=4, random_state=50)
gbc.fit(X_train_copies, y_train_copies)
predictions_gbc = gbc.predict(X_test)

print("Gradient Boosting Classification Report:")
print(classification_report(y_test, predictions_gbc))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_gbc))

SVM Classification Report:
              precision    recall  f1-score   support

         0.0       0.88      0.56      0.69      1941
         1.0       0.22      0.61      0.33       144
         2.0       0.38      0.66      0.48       615

    accuracy                           0.59      2700
   macro avg       0.50      0.61      0.50      2700
weighted avg       0.73      0.59      0.62      2700

Confusion Matrix:
[[1088  225  628]
 [  19   88   37]
 [ 124   84  407]]
Random Forest Classification Report:
              precision    recall  f1-score   support

         0.0       0.85      0.94      0.90      1941
         1.0       0.66      0.51      0.57       144
         2.0       0.74      0.53      0.61       615

    accuracy                           0.83      2700
   macro avg       0.75      0.66      0.70      2700
weighted avg       0.82      0.83      0.81      2700

Confusion Matrix:
[[1833   12   96]
 [  51   73   20]
 [ 266   25  324]]
Gradient Boosting Classifica

In [19]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

# 建立决策树模型
dt = DecisionTreeClassifier(random_state=50)
dt.fit(X_train_copies, y_train_copies)
predictions_dt = dt.predict(X_test)

# 打印决策树分类报告和混淆矩阵
print("Decision Tree Classification Report:")
print(classification_report(y_test, predictions_dt))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_dt))

# 建立k-Nearest Neighbors模型
knn = KNeighborsClassifier()
knn.fit(X_train_copies, y_train_copies)
predictions_knn = knn.predict(X_test)

# 打印k-Nearest Neighbors分类报告和混淆矩阵
print("k-Nearest Neighbors Classification Report:")
print(classification_report(y_test, predictions_knn))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_knn))

# 建立Logistic Regression模型
lr = LogisticRegression(max_iter=1000, random_state=50)
lr.fit(X_train_copies, y_train_copies)
predictions_lr = lr.predict(X_test)
print("Logistic Regression Classification Report:")
print(classification_report(y_test, predictions_lr))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_lr))

Decision Tree Classification Report:
              precision    recall  f1-score   support

         0.0       0.85      0.85      0.85      1941
         1.0       0.39      0.42      0.41       144
         2.0       0.55      0.53      0.54       615

    accuracy                           0.76      2700
   macro avg       0.60      0.60      0.60      2700
weighted avg       0.76      0.76      0.76      2700

Confusion Matrix:
[[1659   44  238]
 [  52   60   32]
 [ 238   48  329]]
k-Nearest Neighbors Classification Report:
              precision    recall  f1-score   support

         0.0       0.83      0.77      0.80      1941
         1.0       0.29      0.31      0.30       144
         2.0       0.43      0.52      0.47       615

    accuracy                           0.69      2700
   macro avg       0.52      0.53      0.52      2700
weighted avg       0.71      0.69      0.70      2700

Confusion Matrix:
[[1490   72  379]
 [  54   45   45]
 [ 255   38  322]]
Logistic Reg

/home/qiuyong/.conda/envs/LiIonMl/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [20]:
import numpy as np
from sklearn.metrics import accuracy_score
probs_rf = rf.predict_proba(X_test)
probs_dt = dt.predict_proba(X_test)
probs_knn = knn.predict_proba(X_test)
weighted_avg_probs = 0.4 * probs_rf[:, 0] + 0.3 * probs_dt[:, 0] + 0.3 * probs_knn[:, 0]
threshold = 0.4
final_predictions = np.where(weighted_avg_probs > threshold,0,predictions_rf)
accuracy = accuracy_score(y_test, final_predictions)
conf_matrix = confusion_matrix(y_test, final_predictions)

print("混淆矩阵:")
print(conf_matrix)
print("加权平均预测准确率:", accuracy)

混淆矩阵:
[[1878   10   53]
 [  68   59   17]
 [ 332   16  267]]
加权平均预测准确率: 0.8162962962962963


In [21]:
import numpy as np
from sklearn.metrics import accuracy_score
probs_rf = rf.predict_proba(X_test)
probs_dt = dt.predict_proba(X_test)
probs_knn = knn.predict_proba(X_test)
weighted_avg_probs = 0.5 * probs_rf[:, 0] + 0.3 * probs_dt[:, 0] + 0.2 * probs_knn[:, 0]
threshold = 0.4
final_predictions = np.where(weighted_avg_probs > threshold,0,predictions_rf)
accuracy = accuracy_score(y_test, final_predictions)
conf_matrix = confusion_matrix(y_test, final_predictions)

print("混淆矩阵:")
print(conf_matrix)
print("加权平均预测准确率:", accuracy)

混淆矩阵:
[[1876   10   55]
 [  64   62   18]
 [ 317   18  280]]
加权平均预测准确率: 0.8214814814814815
