In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
data = pd.read_csv('./MOF.csv',encoding='latin1')
selected_data = data.iloc[:7032, 15:]
print(selected_data)

             ¦Á      LCD      PLD     LFPD    cm3_g  ASA_m2_cm3  ASA_m2_g  \
0     10.467562  5.23722  3.37327  5.23722  1.95599     430.123   219.900   
1      8.827184  6.10125  4.48850  6.10125  2.11606    1211.940   572.736   
2      7.682237  6.64156  4.20343  6.64156  1.63514     826.484   505.451   
3      7.669237  5.13371  3.48538  5.13371  1.96189     431.041   219.707   
4      7.052866  5.46070  3.36863  5.46070  1.51914     446.079   293.640   
...         ...      ...      ...      ...      ...         ...       ...   
7026   0.058403  4.09342  2.99680  4.09342  1.03370       0.000     0.000   
7027   0.000000  3.58736  2.63519  3.53963  2.22163       0.000     0.000   
7028   0.000000  3.75474  2.61308  3.30325  1.68459       0.000     0.000   
7029   0.000000  3.43067  2.87760  3.39852  1.68645       0.000     0.000   
7030   0.000000  3.84984  2.72650  3.32788  1.35854       0.000     0.000   

      NASA_m2_cm3  NASA_m2_g   AV_VF  AV_cm3_g  NAV_cm3_g  Has_OMS  SOCERE 

In [3]:
numpy_array = selected_data.to_numpy()
print (numpy_array)



[[10.46756154  5.23722     3.37327    ...  1.          1.
   1.        ]
 [ 8.8271839   6.10125     4.4885     ...  0.          1.
   1.        ]
 [ 7.68223746  6.64156     4.20343    ...  1.          1.
   1.        ]
 ...
 [ 0.          3.75474     2.61308    ...  1.          0.
   0.        ]
 [ 0.          3.43067     2.8776     ...  1.          0.
   0.        ]
 [ 0.          3.84984     2.7265     ...  0.          0.
   0.        ]]


In [4]:
from sklearn.preprocessing import MinMaxScaler
Mm = MinMaxScaler()
X=selected_data.iloc[:, :].to_numpy()
print(X[1])
data = Mm.fit_transform(X)#归一化处理，为后面的监督学习

[8.8271839e+00 6.1012500e+00 4.4885000e+00 6.1012500e+00 2.1160600e+00
 1.2119400e+03 5.7273600e+02 0.0000000e+00 0.0000000e+00 4.7540000e-01
 2.2466300e-01 0.0000000e+00 0.0000000e+00 1.0000000e+00 1.0000000e+00]


In [5]:
from sklearn.model_selection import train_test_split

# 提取特征数据和目标变量
features = numpy_array[:, :-2]
features1 = numpy_array[:, :-2]
target = numpy_array[:, -2]
print(target)
print(features)
#X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=999)
#X_train1, X_test1, y_train1, y_test1 = train_test_split(features1, target, test_size=0.3, random_state=999)

[1. 1. 1. ... 0. 0. 0.]
[[10.46756154  5.23722     3.37327    ...  0.191105    0.
   1.        ]
 [ 8.8271839   6.10125     4.4885     ...  0.224663    0.
   0.        ]
 [ 7.68223746  6.64156     4.20343    ...  0.25747     0.
   1.        ]
 ...
 [ 0.          3.75474     2.61308    ...  0.273064    0.
   1.        ]
 [ 0.          3.43067     2.8776     ...  0.238726    0.
   1.        ]
 [ 0.          3.84984     2.7265     ...  0.350964    0.
   0.        ]]


In [6]:
import numpy as np
from sklearn.model_selection import train_test_split

# 原始的训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=999)

# 找到标签为1的索引
index_of_ones = np.where(y_train == 1)[0]

# 复制标签为1的数据多份
num_copies_1 = 50  # 假设需要复制20份
index_to_copy_1 = np.random.choice(index_of_ones, size=len(index_of_ones)*num_copies_1, replace=True)

# 将标签为1的数据复制多份并添加到训练集中
X_train_copies = np.concatenate([X_train, X_train[index_to_copy_1]])
y_train_copies = np.concatenate([y_train, y_train[index_to_copy_1]])

# 找到标签为2的索引
index_of_twos = np.where(y_train == 2)[0]

# 复制标签为2的数据多份
num_copies_2 = 10  # 假设需要复制10份
index_to_copy_2 = np.random.choice(index_of_twos, size=len(index_of_twos)*num_copies_2, replace=True)

# 将标签为2的数据复制多份并添加到训练集中
X_train_copies = np.concatenate([X_train_copies, X_train[index_to_copy_2]])
y_train_copies = np.concatenate([y_train_copies, y_train[index_to_copy_2]])

index_of_0s = np.where(y_train == 0)[0]

# 复制标签为2的数据多份
num_copies_0 = 2  # 假设需要复制10份
index_to_copy_0 = np.random.choice(index_of_0s, size=len(index_of_0s)*num_copies_0, replace=True)

# 将标签为2的数据复制多份并添加到训练集中
X_train_copies = np.concatenate([X_train_copies, X_train[index_to_copy_0]])
y_train_copies = np.concatenate([y_train_copies, y_train[index_to_copy_0]])

In [7]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

# 建立SVM模型
svm = SVC(kernel='linear', random_state=50,C= 1)
svm.fit(X_train_copies, y_train_copies)
predictions_svm = svm.predict(X_test)

# 打印SVM分类报告和混淆矩阵
print("SVM Classification Report:")
print(classification_report(y_test, predictions_svm))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_svm))

# 建立随机森林模型
rf = RandomForestClassifier(n_estimators=100, random_state=50)
rf.fit(X_train_copies, y_train_copies)
predictions_rf = rf.predict(X_test)

# 打印随机森林分类报告和混淆矩阵
print("Random Forest Classification Report:")
print(classification_report(y_test, predictions_rf))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_rf))

# 建立梯度提升树模型
gbc = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=4, random_state=50)
gbc.fit(X_train_copies, y_train_copies)
predictions_gbc = gbc.predict(X_test)

# 打印梯度提升树分类报告和混淆矩阵
print("Gradient Boosting Classification Report:")
print(classification_report(y_test, predictions_gbc))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_gbc))


SVM Classification Report:
              precision    recall  f1-score   support

         0.0       0.94      0.75      0.83      1578
         1.0       0.34      0.76      0.47       105
         2.0       0.44      0.64      0.52       427

    accuracy                           0.73      2110
   macro avg       0.57      0.72      0.61      2110
weighted avg       0.81      0.73      0.75      2110

Confusion Matrix:
[[1183   74  321]
 [   4   80   21]
 [  73   82  272]]
Random Forest Classification Report:
              precision    recall  f1-score   support

         0.0       0.90      0.94      0.92      1578
         1.0       0.74      0.68      0.71       105
         2.0       0.68      0.58      0.62       427

    accuracy                           0.85      2110
   macro avg       0.77      0.73      0.75      2110
weighted avg       0.84      0.85      0.85      2110

Confusion Matrix:
[[1480    9   89]
 [   6   71   28]
 [ 164   16  247]]
Gradient Boosting Classifica

In [8]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

# 建立决策树模型
dt = DecisionTreeClassifier(random_state=50)
dt.fit(X_train_copies, y_train_copies)
predictions_dt = dt.predict(X_test)

# 打印决策树分类报告和混淆矩阵
print("Decision Tree Classification Report:")
print(classification_report(y_test, predictions_dt))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_dt))

# 建立k-Nearest Neighbors模型
knn = KNeighborsClassifier()
knn.fit(X_train_copies, y_train_copies)
predictions_knn = knn.predict(X_test)

# 打印k-Nearest Neighbors分类报告和混淆矩阵
print("k-Nearest Neighbors Classification Report:")
print(classification_report(y_test, predictions_knn))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_knn))

# 建立Logistic Regression模型
lr = LogisticRegression(max_iter=1000, random_state=50)
lr.fit(X_train_copies, y_train_copies)
predictions_lr = lr.predict(X_test)

# 打印Logistic Regression分类报告和混淆矩阵
print("Logistic Regression Classification Report:")
print(classification_report(y_test, predictions_lr))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_lr))


Decision Tree Classification Report:
              precision    recall  f1-score   support

         0.0       0.87      0.88      0.87      1578
         1.0       0.61      0.60      0.61       105
         2.0       0.52      0.51      0.51       427

    accuracy                           0.79      2110
   macro avg       0.67      0.66      0.66      2110
weighted avg       0.79      0.79      0.79      2110

Confusion Matrix:
[[1385   16  177]
 [  16   63   26]
 [ 187   24  216]]
k-Nearest Neighbors Classification Report:
              precision    recall  f1-score   support

         0.0       0.83      0.76      0.79      1578
         1.0       0.22      0.30      0.25       105
         2.0       0.38      0.46      0.42       427

    accuracy                           0.68      2110
   macro avg       0.48      0.51      0.49      2110
weighted avg       0.71      0.68      0.69      2110

Confusion Matrix:
[[1196   85  297]
 [  45   32   28]
 [ 200   30  197]]
Logistic Reg

/home/qiuyong/.conda/envs/LiIonMl/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [9]:
import numpy as np
from sklearn.metrics import accuracy_score
# 假设predictions_rf、predictions_dt、predictions_knn是随机森林、决策树和k-Nearest Neighbors的预测结果
# 分别对应模型的类别概率
probs_rf = rf.predict_proba(X_test)
probs_dt = dt.predict_proba(X_test)
probs_knn = knn.predict_proba(X_test)

# 对预测类型1的加权平均
weighted_avg_probs = 0.4 * probs_rf[:, 0] + 0.3 * probs_dt[:, 0] + 0.3 * probs_knn[:, 0]
#print(probs_rf[:, 0])
# 设置阈值，当加权平均概率超过阈值时，认定为类型1
threshold = 0.4

# 根据阈值判断最终的预测类型
final_predictions = np.where(weighted_avg_probs > threshold,0,predictions_rf)
# 计算准确率
accuracy = accuracy_score(y_test, final_predictions)
conf_matrix = confusion_matrix(y_test, final_predictions)

print("混淆矩阵:")
print(conf_matrix)
print("加权平均预测准确率:", accuracy)

混淆矩阵:
[[1529    7   42]
 [  17   65   23]
 [ 246   13  168]]
加权平均预测准确率: 0.8350710900473933


In [10]:
import numpy as np
from sklearn.model_selection import train_test_split

# 原始的训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=999)

# 找到标签为1的索引
index_of_ones = np.where(y_train == 1)[0]

# 复制标签为1的数据多份
num_copies_1 = 30  # 假设需要复制20份
index_to_copy_1 = np.random.choice(index_of_ones, size=len(index_of_ones)*num_copies_1, replace=True)

# 将标签为1的数据复制多份并添加到训练集中
X_train_copies = np.concatenate([X_train, X_train[index_to_copy_1]])
y_train_copies = np.concatenate([y_train, y_train[index_to_copy_1]])

# 找到标签为2的索引
index_of_twos = np.where(y_train == 2)[0]

# 复制标签为2的数据多份
num_copies_2 = 10  # 假设需要复制10份
index_to_copy_2 = np.random.choice(index_of_twos, size=len(index_of_twos)*num_copies_2, replace=True)

# 将标签为2的数据复制多份并添加到训练集中
X_train_copies = np.concatenate([X_train_copies, X_train[index_to_copy_2]])
y_train_copies = np.concatenate([y_train_copies, y_train[index_to_copy_2]])

index_of_0s = np.where(y_train == 0)[0]

# 复制标签为2的数据多份
num_copies_0 = 2  # 假设需要复制10份
index_to_copy_0 = np.random.choice(index_of_0s, size=len(index_of_0s)*num_copies_0, replace=True)

# 将标签为2的数据复制多份并添加到训练集中
X_train_copies = np.concatenate([X_train_copies, X_train[index_to_copy_0]])
y_train_copies = np.concatenate([y_train_copies, y_train[index_to_copy_0]])

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

# 建立SVM模型
svm = SVC(kernel='linear', random_state=50,C= 1)
svm.fit(X_train_copies, y_train_copies)
predictions_svm = svm.predict(X_test)

# 打印SVM分类报告和混淆矩阵
print("SVM Classification Report:")
print(classification_report(y_test, predictions_svm))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_svm))

# 建立随机森林模型
rf = RandomForestClassifier(n_estimators=100, random_state=50)
rf.fit(X_train_copies, y_train_copies)
predictions_rf = rf.predict(X_test)

# 打印随机森林分类报告和混淆矩阵
print("Random Forest Classification Report:")
print(classification_report(y_test, predictions_rf))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_rf))

# 建立梯度提升树模型
gbc = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=4, random_state=50)
gbc.fit(X_train_copies, y_train_copies)
predictions_gbc = gbc.predict(X_test)

# 打印梯度提升树分类报告和混淆矩阵
print("Gradient Boosting Classification Report:")
print(classification_report(y_test, predictions_gbc))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_gbc))

SVM Classification Report:
              precision    recall  f1-score   support

         0.0       0.94      0.74      0.83      1578
         1.0       0.38      0.70      0.49       105
         2.0       0.44      0.69      0.54       427

    accuracy                           0.73      2110
   macro avg       0.59      0.71      0.62      2110
weighted avg       0.81      0.73      0.75      2110

Confusion Matrix:
[[1171   64  343]
 [   4   73   28]
 [  75   56  296]]
Random Forest Classification Report:
              precision    recall  f1-score   support

         0.0       0.90      0.94      0.92      1578
         1.0       0.72      0.69      0.70       105
         2.0       0.69      0.58      0.63       427

    accuracy                           0.85      2110
   macro avg       0.77      0.73      0.75      2110
weighted avg       0.85      0.85      0.85      2110

Confusion Matrix:
[[1485   10   83]
 [   6   72   27]
 [ 163   18  246]]
Gradient Boosting Classifica

In [12]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

# 建立决策树模型
dt = DecisionTreeClassifier(random_state=50)
dt.fit(X_train_copies, y_train_copies)
predictions_dt = dt.predict(X_test)

# 打印决策树分类报告和混淆矩阵
print("Decision Tree Classification Report:")
print(classification_report(y_test, predictions_dt))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_dt))

# 建立k-Nearest Neighbors模型
knn = KNeighborsClassifier()
knn.fit(X_train_copies, y_train_copies)
predictions_knn = knn.predict(X_test)

# 打印k-Nearest Neighbors分类报告和混淆矩阵
print("k-Nearest Neighbors Classification Report:")
print(classification_report(y_test, predictions_knn))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_knn))

# 建立Logistic Regression模型
lr = LogisticRegression(max_iter=1000, random_state=50)
lr.fit(X_train_copies, y_train_copies)
predictions_lr = lr.predict(X_test)

# 打印Logistic Regression分类报告和混淆矩阵
print("Logistic Regression Classification Report:")
print(classification_report(y_test, predictions_lr))
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions_lr))

Decision Tree Classification Report:
              precision    recall  f1-score   support

         0.0       0.89      0.89      0.89      1578
         1.0       0.62      0.67      0.64       105
         2.0       0.56      0.55      0.56       427

    accuracy                           0.81      2110
   macro avg       0.69      0.70      0.70      2110
weighted avg       0.81      0.81      0.81      2110

Confusion Matrix:
[[1400   22  156]
 [   8   70   27]
 [ 170   21  236]]
k-Nearest Neighbors Classification Report:
              precision    recall  f1-score   support

         0.0       0.83      0.75      0.79      1578
         1.0       0.22      0.31      0.26       105
         2.0       0.37      0.46      0.41       427

    accuracy                           0.67      2110
   macro avg       0.47      0.51      0.49      2110
weighted avg       0.71      0.67      0.69      2110

Confusion Matrix:
[[1185   85  308]
 [  40   33   32]
 [ 201   30  196]]
Logistic Reg

/home/qiuyong/.conda/envs/LiIonMl/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [13]:
import numpy as np
from sklearn.metrics import accuracy_score
# 假设predictions_rf、predictions_dt、predictions_knn是随机森林、决策树和k-Nearest Neighbors的预测结果
# 分别对应模型的类别概率
probs_rf = rf.predict_proba(X_test)
probs_dt = dt.predict_proba(X_test)
probs_knn = knn.predict_proba(X_test)

# 对预测类型1的加权平均
weighted_avg_probs = 0.4 * probs_rf[:, 0] + 0.3 * probs_dt[:, 0] + 0.3 * probs_knn[:, 0]
#print(probs_rf[:, 0])
# 设置阈值，当加权平均概率超过阈值时，认定为类型1
threshold = 0.4

# 根据阈值判断最终的预测类型
final_predictions = np.where(weighted_avg_probs > threshold,0,predictions_rf)
# 计算准确率
accuracy = accuracy_score(y_test, final_predictions)
conf_matrix = confusion_matrix(y_test, final_predictions)

print("混淆矩阵:")
print(conf_matrix)
print("加权平均预测准确率:", accuracy)

混淆矩阵:
[[1525    8   45]
 [  13   70   22]
 [ 228   15  184]]
加权平均预测准确率: 0.843127962085308


In [14]:
import numpy as np
from sklearn.metrics import accuracy_score
# 假设predictions_rf、predictions_dt、predictions_knn是随机森林、决策树和k-Nearest Neighbors的预测结果
# 分别对应模型的类别概率
probs_rf = rf.predict_proba(X_test)
probs_dt = dt.predict_proba(X_test)
probs_knn = knn.predict_proba(X_test)

# 对预测类型1的加权平均
weighted_avg_probs = 0.5 * probs_rf[:, 0] + 0.3 * probs_dt[:, 0] + 0.2 * probs_knn[:, 0]
#print(probs_rf[:, 0])
# 设置阈值，当加权平均概率超过阈值时，认定为类型1
threshold = 0.4

# 根据阈值判断最终的预测类型
final_predictions = np.where(weighted_avg_probs > threshold,0,predictions_rf)
# 计算准确率
accuracy = accuracy_score(y_test, final_predictions)
conf_matrix = confusion_matrix(y_test, final_predictions)

print("混淆矩阵:")
print(conf_matrix)
print("加权平均预测准确率:", accuracy)

混淆矩阵:
[[1513    9   56]
 [   8   72   25]
 [ 215   15  197]]
加权平均预测准确率: 0.8445497630331753
